--- !ruby/object:Jumpstart::Configuration
application_name: TheReportingApp
business_name: TheReportingApp
domain: example.com
support_email: support@example.com
default_from_email: Jumpstart <support@example.com>
business_address: |-
  325 Franklin Lane
  Ripon, CA
background_job_processor: async
email_provider: ''
personal_accounts: true
livereload: false
